pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
        echo 'Hello, Maven'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    stage('Example Build') {
    agent { docker 'maven:3.9.3-eclipse-temurin-17' }
    steps {
                sh 'mvn -B clean verify'
            }
        }
    }
  }
  
  

